# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(1316, 885)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_VideoDisplay = QtWidgets.QLabel(widget)
        self.label_VideoDisplay.setText("")
        self.label_VideoDisplay.setObjectName("label_VideoDisplay")
        self.horizontalLayout_2.addWidget(self.label_VideoDisplay)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_laserdisplay = QtWidgets.QLabel(widget)
        self.label_laserdisplay.setText("")
        self.label_laserdisplay.setObjectName("label_laserdisplay")
        self.horizontalLayout_2.addWidget(self.label_laserdisplay)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(widget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 3, 1, 1)
        self.horizontalSlider_SetGain = QtWidgets.QSlider(widget)
        self.horizontalSlider_SetGain.setMinimum(16)
        self.horizontalSlider_SetGain.setMaximum(64)
        self.horizontalSlider_SetGain.setSingleStep(1)
        self.horizontalSlider_SetGain.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_SetGain.setObjectName("horizontalSlider_SetGain")
        self.gridLayout.addWidget(self.horizontalSlider_SetGain, 2, 1, 1, 1)
        self.set_gain = QtWidgets.QLabel(widget)
        self.set_gain.setAlignment(QtCore.Qt.AlignCenter)
        self.set_gain.setObjectName("set_gain")
        self.gridLayout.addWidget(self.set_gain, 2, 0, 1, 1)
        self.horizontalSlider_Setfps = QtWidgets.QSlider(widget)
        self.horizontalSlider_Setfps.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Setfps.setObjectName("horizontalSlider_Setfps")
        self.gridLayout.addWidget(self.horizontalSlider_Setfps, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 3, 1, 1)
        self.lineEdit_Capturenumber = QtWidgets.QLineEdit(widget)
        self.lineEdit_Capturenumber.setObjectName("lineEdit_Capturenumber")
        self.gridLayout.addWidget(self.lineEdit_Capturenumber, 2, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 5, 1, 1)
        self.lineEdit_Savepath = QtWidgets.QLineEdit(widget)
        self.lineEdit_Savepath.setObjectName("lineEdit_Savepath")
        self.gridLayout.addWidget(self.lineEdit_Savepath, 0, 4, 1, 2)
        self.lineEdit_fps = QtWidgets.QLineEdit(widget)
        self.lineEdit_fps.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_fps.sizePolicy().hasHeightForWidth())
        self.lineEdit_fps.setSizePolicy(sizePolicy)
        self.lineEdit_fps.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_fps.setMaxLength(40)
        self.lineEdit_fps.setObjectName("lineEdit_fps")
        self.gridLayout.addWidget(self.lineEdit_fps, 0, 2, 1, 1)
        self.lineEdit_exposuretime = QtWidgets.QLineEdit(widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_exposuretime.sizePolicy().hasHeightForWidth())
        self.lineEdit_exposuretime.setSizePolicy(sizePolicy)
        self.lineEdit_exposuretime.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_exposuretime.setObjectName("lineEdit_exposuretime")
        self.gridLayout.addWidget(self.lineEdit_exposuretime, 1, 2, 1, 1)
        self.set_Exposiretime = QtWidgets.QLabel(widget)
        self.set_Exposiretime.setObjectName("set_Exposiretime")
        self.gridLayout.addWidget(self.set_Exposiretime, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(widget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 3, 1, 1)
        self.horizontalSlider_SetExposure = QtWidgets.QSlider(widget)
        self.horizontalSlider_SetExposure.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_SetExposure.setObjectName("horizontalSlider_SetExposure")
        self.gridLayout.addWidget(self.horizontalSlider_SetExposure, 1, 1, 1, 1)
        self.lineEdit_Captureinterval = QtWidgets.QLineEdit(widget)
        self.lineEdit_Captureinterval.setObjectName("lineEdit_Captureinterval")
        self.gridLayout.addWidget(self.lineEdit_Captureinterval, 1, 4, 1, 1)
        self.set_FPS = QtWidgets.QLabel(widget)
        self.set_FPS.setAlignment(QtCore.Qt.AlignCenter)
        self.set_FPS.setObjectName("set_FPS")
        self.gridLayout.addWidget(self.set_FPS, 0, 0, 1, 1)
        self.lineEdit_gain = QtWidgets.QLineEdit(widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_gain.sizePolicy().hasHeightForWidth())
        self.lineEdit_gain.setSizePolicy(sizePolicy)
        self.lineEdit_gain.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_gain.setObjectName("lineEdit_gain")
        self.gridLayout.addWidget(self.lineEdit_gain, 2, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_OpenCamera = QtWidgets.QPushButton(widget)
        self.label_OpenCamera.setObjectName("label_OpenCamera")
        self.horizontalLayout_3.addWidget(self.label_OpenCamera)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_CloseCamera = QtWidgets.QPushButton(widget)
        self.label_CloseCamera.setObjectName("label_CloseCamera")
        self.horizontalLayout_3.addWidget(self.label_CloseCamera)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.label_CaptureFrame = QtWidgets.QPushButton(widget)
        self.label_CaptureFrame.setObjectName("label_CaptureFrame")
        self.horizontalLayout_3.addWidget(self.label_CaptureFrame)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.label_PlotBloodFlow = QtWidgets.QPushButton(widget)
        self.label_PlotBloodFlow.setObjectName("label_PlotBloodFlow")
        self.horizontalLayout_3.addWidget(self.label_PlotBloodFlow)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.Label_quit = QtWidgets.QPushButton(widget)
        self.Label_quit.setObjectName("Label_quit")
        self.horizontalLayout_3.addWidget(self.Label_quit)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.pushButton_v1 = QtWidgets.QPushButton(widget)
        self.pushButton_v1.setObjectName("pushButton_v1")
        self.horizontalLayout.addWidget(self.pushButton_v1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.pushButton_2 = QtWidgets.QPushButton(widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Form"))
        self.label_5.setText(_translate("widget", "capture number:"))
        self.set_gain.setText(_translate("widget", "gain"))
        self.label_2.setText(_translate("widget", "capture interval:"))
        self.lineEdit_Capturenumber.setText(_translate("widget", "5"))
        self.label_3.setText(_translate("widget", "ms"))
        self.lineEdit_Savepath.setText(_translate("widget", "D:\\\\LaserImage"))
        self.set_Exposiretime.setText(_translate("widget", "Exposure time："))
        self.label.setText(_translate("widget", "save path:"))
        self.lineEdit_Captureinterval.setText(_translate("widget", "100"))
        self.set_FPS.setText(_translate("widget", "FPS"))
        self.label_OpenCamera.setText(_translate("widget", "open camera"))
        self.label_CloseCamera.setText(_translate("widget", "close camera"))
        self.label_CaptureFrame.setText(_translate("widget", "capture frame"))
        self.label_PlotBloodFlow.setText(_translate("widget", "plot"))
        self.Label_quit.setText(_translate("widget", "quit"))
        self.pushButton_v1.setText(_translate("widget", "v"))
        self.pushButton_2.setText(_translate("widget", "export data"))

